-- init.sql

-- Criar extensão para suportar UUIDs, se ainda não estiver ativada
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Criar tabela de usuários com UUID como chave primária
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(100) PRIMARY KEY INT UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  eliminated VARCHAR(100) NOT NULL
);

-- Inserir 20 usuários com nomes e countrys aleatórios
INSERT INTO users (id, name, eliminated)
VALUES
  (1, "", "no"),
  (2, "", "no"),
  (3, "", "no"),
  (4, "", "no"),
  (5, "", "no"),
  (6, "", "no"),
  (7, "", "no"),
  (8, "", "no"),
  (9, "", "no"),
  (10, "", "no"),
  (11, "", "no"),
  (12, "", "no"),
  (13, "", "no"),
  (14, "", "no"),
  (15, "", "no"),
  (16, "", "no"),
  (17, "", "no"),
  (18, "", "no"),
  (19, "", "no"),
  (20, "", "no"),
  (21, "", "no"),
  (22, "", "no"),
  (23, "", "no"),
  (24, "", "no"),
  (25, "", "no"),
  (26, "", "no"),
  (27, "", "no"),
  (28, "", "no"),
  (29, "", "no"),
  (30, "", "no"),
  (31, "", "no"),
  (32, "", "no"),
  (33, "", "no"),
  (34, "", "no"),
  (35, "", "no"),
  (36, "", "no"),
  (37, "", "no"),
  (38, "", "no"),
  (39, "", "no"),
  (40, "", "no"),
  (41, "", "no"),
  (42, "", "no"),
  (43, "", "no"),
  (44, "", "no"),
  (45, "", "no"),
  (46, "", "no"),
  (47, "", "no"),
  (48, "", "no"),
  (49, "", "no"),
  (50, "", "no"),
  (51, "", "no"),
  (52, "", "no"),
  (53, "", "no"),
  (54, "", "no"),
  (55, "", "no"),
  (56, "", "no"),
  (57, "", "no"),
  (58, "", "no"),
  (59, "", "no"),
  (60, "", "no"),
  (61, "", "no"),
  (62, "", "no"),
  (63, "", "no"),
  (64, "", "no"),
  (65, "", "no"),
  (66, "", "no"),
  (67, "", "no"),
  (68, "", "no"),
  (69, "", "no"),
  (70, "", "no"),
  (71, "", "no"),
  (72, "", "no"),
  (73, "", "no"),
  (74, "", "no"),
  (75, "", "no"),
  (76, "", "no"),
  (77, "", "no"),
  (78, "", "no"),
  (79, "", "no"),
  (80, "", "no"),